//PImage Caixa;
//PImage Isopor;
//PImage Detergente;
//PImage GarrafaVidro1;
//PImage GarrafaVidro2;
//PImage Garrafa;
//PImage Jornal;
//PImage LataGrande;
//PImage LataPequena;
//PImage LataRefri;
//PImage Leite;
//PImage Mug;
//PImage Pizza;
//PImage PoteVidro;
//PImage Pressurizada;
//PImage Saco;
boolean ReciclavelSpawned = false;
String[] Metal = {"LataPequena","LataGrande","LataRefri"};
String[] Vidro = {"GarrafaVidro1","GarrafaVidro2","PoteVidro"};
String[] Papel = {"Caixa","Jornal","Saco"};
String[] Plastico = {"Garrafa","Leite","Detergente"};
String[] Outros = {"Isopor", "Mug", "Pizza", "Pressurizada"};
String[][] Todas = {Metal, Vidro, Papel, Plastico, Outros};
