boolean Reciclagem1 = false;
boolean ReciclavelSpawned = false;
boolean Reciclavel1Completed = false;
ArrayList<String> Metal = new ArrayList<String>(Arrays.asList("LataPequena", "LataGrande", "LataRefri"));
ArrayList<String> Vidro = new ArrayList<String>(Arrays.asList("GarrafaVidro1", "GarrafaVidro2", "PoteVidro"));
ArrayList<String> Papel = new ArrayList<String>(Arrays.asList("Caixa", "Jornal", "Saco"));
ArrayList<String> Plastico = new ArrayList<String>(Arrays.asList("garrafa", "Leite", "Detergente"));
ArrayList<String> Outros = new ArrayList<String>(Arrays.asList("CopoIsopor", "Mug", "Pizza", "Pressurizada"));
ArrayList<ArrayList<String>> Todas = new ArrayList<ArrayList<String>>();
PFont Puff;
PImage LixoMetal;
PImage LixoOrganico;
PImage LixoPapel;
PImage LixoPlastico;
PImage LixoVidro;
boolean TrashInMouse = false;
PImage ItemReciclavel;
